using System;
using System.IO;
using System.Linq;
using OsLib;
using Xunit;
namespace JsonPit.Tests;
/// <summary>
/// Tests for the timed-ticket master flag protocol and the 6-step MergeChanges workflow.
/// </summary>
public sealed class MasterTicketTests : IDisposable
{
	private readonly RaiPath root;
	private readonly TimeSpan originalDuration;
	public MasterTicketTests()
	{
		originalDuration = MasterFlagFile.TicketDuration;
		root = new RaiPath(Path.GetTempPath()) / "RAIkeep" / "jsonpit-tests" / "master-ticket";
		Cleanup();
		root.mkdir();
	}
	public void Dispose()
	{
		MasterFlagFile.TicketDuration = originalDuration;
		Cleanup();
	}
	private void Cleanup()
	{
		try
		{
			if (root.Exists())
				new RaiFile(root.Path).rmdir(depth: 10, deleteFiles: true);
		}
		catch { }
	}
	#region Machine name validation
	[Theory]
	[InlineData("localhost")]
	[InlineData("ubuntu")]
	[InlineData("debian")]
	[InlineData("raspberrypi")]
	[InlineData("default")]
	[InlineData("docker")]
	[InlineData("buildkitsandbox")]
	[InlineData("runner")]
	public void ValidateMachineName_RejectsGenericNames(string name)
	{
		Assert.False(ProcessFlagFile.ValidateMachineName(name));
	}
	[Theory]
	[InlineData("DESKTOP-A1B2C3D")]
	[InlineData("WIN-ABCDEF12345")]
	[InlineData("ip-172-31-42-17")]
	[InlineData("vm-0a1b2c3d4e5f")]
	public void ValidateMachineName_RejectsAutoGeneratedNames(string name)
	{
		Assert.False(ProcessFlagFile.ValidateMachineName(name));
	}
	[Theory]
	[InlineData("Nkosikazi")]
	[InlineData("Mzansi")]
	[InlineData("devbox")]
	[InlineData("staging-01")]
	public void ValidateMachineName_AcceptsProperNames(string name)
	{
		Assert.True(ProcessFlagFile.ValidateMachineName(name));
	}
	[Theory]
	[InlineData(null)]
	[InlineData("")]
	[InlineData("  ")]
	[InlineData("ab")]
	public void ValidateMachineName_RejectsTooShortOrEmpty(string name)
	{
		Assert.False(ProcessFlagFile.ValidateMachineName(name));
	}
	[Fact]
	public void ValidateMachineName_CurrentMachineHasProperName()
	{
		// This test will fail if the machine running the test suite has a generic hostname.
		// If it fails, rename your machine — see CONFIGURE_SERVER.md.
		Assert.True(
			ProcessFlagFile.ValidateMachineName(),
			$"Machine name '{Environment.MachineName}' is generic or auto-generated. " +
			"Set a proper hostname — see CONFIGURE_SERVER.md in the JsonPit project.");
	}
	#endregion
	#region ProcessFlagFile naming
	[Fact]
	public void FlagName_IncludesMachineNameAndSubscriber()
	{
		var name = ProcessFlagFile.FlagName("pits");
		Assert.Equal($"{Environment.MachineName}-pits", name);
	}
	[Fact]
	public void FlagName_FallsBackToProcessNameWhenNoSubscriber()
	{
		var name = ProcessFlagFile.FlagName();
		Assert.StartsWith($"{Environment.MachineName}-", name);
		Assert.NotEqual($"{Environment.MachineName}-", name); // has something after the dash
	}
	[Fact]
	public void ProcessFlagFile_CreatesFileWithCorrectName()
	{
		var dir = (root / "flag-naming").mkdir();
		var flag = new ProcessFlagFile(dir, "RAIkeep");
		flag.Update();
		Assert.True(flag.Exists());
		Assert.Equal($"{Environment.MachineName}-RAIkeep", flag.Name);
	}
	[Fact]
	public void ProcessFlagFile_ContentContainsMachineAndProcessInfo()
	{
		var dir = (root / "flag-content").mkdir();
		var flag = new ProcessFlagFile(dir, "Nomsa");
		flag.Update();
		flag.Read();
		// Content should be "MachineName:ProcessName:PID|timestamp"
		Assert.Contains(Environment.MachineName, flag.Lines[0]);
		Assert.Contains("|", flag.Lines[0]);
	}
	#endregion
	#region MasterFlagFile ticket tests
	[Fact]
	public void IsExpired_TrueForFreshEmptyFlag()
	{
		var dir = (root / "expired-empty").mkdir();
		var flag = new MasterFlagFile(dir, "Master");
		Assert.True(flag.IsExpired);
	}
	[Fact]
	public void IsExpired_FalseAfterUpdate()
	{
		var dir = (root / "not-expired").mkdir();
		var flag = new MasterFlagFile(dir, "Master");
		flag.Update();
		Assert.False(flag.IsExpired);
	}
	[Fact]
	public void IsExpired_TrueWhenTicketAgedOut()
	{
		MasterFlagFile.TicketDuration = TimeSpan.FromMilliseconds(1);
		var dir = (root / "aged-out").mkdir();
		var flag = new MasterFlagFile(dir, "Master");
		flag.Update(time: DateTimeOffset.UtcNow - TimeSpan.FromSeconds(5));
		Assert.True(flag.IsExpired);
	}
	[Fact]
	public void IsOwnedByMe_TrueWhenThisMachineOwnsValidTicket()
	{
		var dir = (root / "owned-by-me").mkdir();
		var flag = new MasterFlagFile(dir, "Master");
		flag.Update();
		Assert.True(flag.IsOwnedByMe);
	}
	[Fact]
	public void IsOwnedByMe_FalseWhenOtherMachineOwns()
	{
		var dir = (root / "owned-other").mkdir();
		var flag = new MasterFlagFile(dir, "Master", server: "OtherMachine");
		Assert.False(flag.IsOwnedByMe);
		Assert.False(flag.IsExpired);
	}
	[Fact]
	public void TryClaim_SucceedsWhenExpired()
	{
		MasterFlagFile.TicketDuration = TimeSpan.FromMilliseconds(1);
		var dir = (root / "claim-expired").mkdir();
		var flag = new MasterFlagFile(dir, "Master", server: "OtherMachine");
		flag.Update(time: DateTimeOffset.UtcNow - TimeSpan.FromSeconds(5), originator: "OtherMachine");
		Assert.True(flag.IsExpired);
		Assert.True(flag.TryClaim());
		Assert.Equal(Environment.MachineName, flag.Originator);
	}
	[Fact]
	public void TryClaim_FailsWhenOtherMachineHasValidTicket()
	{
		var dir = (root / "claim-refused").mkdir();
		var flag = new MasterFlagFile(dir, "Master", server: "OtherMachine");
		Assert.False(flag.IsExpired);
		Assert.False(flag.TryClaim());
		Assert.Equal("OtherMachine", flag.Originator);
	}
	[Fact]
	public void TryClaim_RenewsOwnTicket()
	{
		var dir = (root / "claim-renew").mkdir();
		var flag = new MasterFlagFile(dir, "Master");
		flag.Update();
		var firstTime = flag.Time;
		System.Threading.Thread.Sleep(10);
		Assert.True(flag.TryClaim());
		Assert.True(flag.Time > firstTime);
	}
	#endregion
	#region TryAcquireMaster integration tests
	[Fact]
	public void TryAcquireMaster_SucceedsForUnflagged()
	{
		var pitPath = (root / "unflagged-pit").mkdir();
		var pit = new Pit(pitPath, readOnly: false, autoload: false, unflagged: true);
		Assert.True(pit.TryAcquireMaster());
	}
	[Fact]
	public void TryAcquireMaster_SucceedsWhenNobodyElseActive()
	{
		var pitPath = (root / "sole-pit").mkdir();
		var pit = new Pit(pitPath, readOnly: false, autoload: false, subscriber: "pits");
		Assert.True(pit.TryAcquireMaster());
	}
	[Fact]
	public void TryAcquireMaster_FailsWhenOtherMachineHoldsTicket()
	{
		var pitPath = (root / "blocked-pit").mkdir();
		var otherFlag = new MasterFlagFile(pitPath, "Master", server: "FarAwayServer");
		Assert.False(otherFlag.IsExpired);
		var pit = new Pit(pitPath, readOnly: false, autoload: false, subscriber: "pits");
		Assert.False(pit.TryAcquireMaster());
	}
	[Fact]
	public void TryAcquireMaster_SucceedsAfterOtherMachineTicketExpires()
	{
		MasterFlagFile.TicketDuration = TimeSpan.FromMilliseconds(1);
		var pitPath = (root / "expired-other-pit").mkdir();
		var otherFlag = new MasterFlagFile(pitPath, "Master", server: "FarAwayServer");
		otherFlag.Update(time: DateTimeOffset.UtcNow - TimeSpan.FromSeconds(5), originator: "FarAwayServer");
		Assert.True(otherFlag.IsExpired);
		var pit = new Pit(pitPath, readOnly: false, autoload: false, subscriber: "pits");
		Assert.True(pit.TryAcquireMaster());
		Assert.Equal(Environment.MachineName, pit.MasterFlag().Originator);
	}
	[Fact]
	public void TryAcquireMaster_RefusedWhenForeignProcessRecentlyActive()
	{
		MasterFlagFile.TicketDuration = TimeSpan.FromMilliseconds(1);
		var pitPath = (root / "foreign-active-pit").mkdir();
		// Plant an expired master flag
		var masterFlag = new MasterFlagFile(pitPath, "Master", server: "OldMaster");
		masterFlag.Update(time: DateTimeOffset.UtcNow - TimeSpan.FromSeconds(5), originator: "OldMaster");
		Assert.True(masterFlag.IsExpired);
		// Plant a *recent* foreign process flag: "FarAwayServer-RAIkeep.flag"
		MasterFlagFile.TicketDuration = TimeSpan.FromSeconds(60);
		var foreignFlag = new TextFile(pitPath, "FarAwayServer-RAIkeep", "flag");
		var recentTimestamp = new TimestampedValue("FarAwayServer:dotnet:1234", DateTimeOffset.UtcNow);
		foreignFlag.Lines = [recentTimestamp.ToString()];
		foreignFlag.Changed = true;
		foreignFlag.Save();
		var pit = new Pit(pitPath, readOnly: false, autoload: false, subscriber: "pits");
		Assert.False(pit.TryAcquireMaster());
	}
	#endregion
	#region Save: master vs client path
	[Fact]
	public void Save_AsMaster_StoresPitFileDirectly()
	{
		var pitPath = (root / "save-master").mkdir();
		var pit = new Pit(pitPath, readOnly: false, autoload: false, subscriber: "pits");
		pit.Add(new PitItem("Item1"));
		pit.Save(force: true);
		Assert.True(pit.JsonFile.Exists());
		var changeFiles = pit.PitDir.EnumerateFiles("*.json")
			.Where(f => f.Name != pit.JsonFile.Name).ToList();
		Assert.Empty(changeFiles);
	}
	[Fact]
	public void Save_AsClient_WritesChangeFilesOnly()
	{
		var pitPath = (root / "save-client").mkdir();
		var otherFlag = new MasterFlagFile(pitPath, "Master", server: "TheMaster");
		var pit = new Pit(pitPath, readOnly: false, autoload: false, subscriber: "pits");
		pit.Add(new PitItem("ClientItem"));
		pit.Save(force: true);
		var changeFiles = pit.PitDir.EnumerateFiles("*.json")
			.Where(f => f.Name != pit.JsonFile.Name).ToList();
		Assert.NotEmpty(changeFiles);
	}
	#endregion
	#region MergeChanges: 6-step workflow
	[Fact]
	public void MergeChanges_MasterMergesClientChangeFiles()
	{
		var pitPath = (root / "merge-master").mkdir();
		var masterPit = new Pit(pitPath, readOnly: false, autoload: false, subscriber: "RAIkeep");
		masterPit.Add(new PitItem("MasterItem"));
		masterPit.Save(force: true);
		var clientItem = new PitItem("ClientItem");
		clientItem.SetProperty(new { Value = 42 });
		masterPit.CreateChangeFile(clientItem, "ClientMachine");
		var reloaded = new Pit(pitPath, readOnly: false, autoload: true, subscriber: "RAIkeep");
		Assert.NotNull(reloaded.Get("MasterItem"));
		Assert.NotNull(reloaded.Get("ClientItem"));
		Assert.Equal(42, reloaded.Get("ClientItem")?["Value"]?.ToObject<int>());
	}
	[Fact]
	public void MergeChanges_ClientMergesButDoesNotDeleteOrStore()
	{
		var pitPath = (root / "merge-client").mkdir();
		var otherFlag = new MasterFlagFile(pitPath, "Master", server: "TheMaster");
		var setupPit = new Pit(pitPath, readOnly: false, autoload: false, unflagged: true);
		setupPit.Add(new PitItem("BaseItem"));
		setupPit.Save(force: true);
		setupPit.CreateChangeFile(new PitItem("PeerItem"), "PeerMachine");
		// Re-plant master flag (setupPit may have overwritten it)
		var masterFlagAgain = new MasterFlagFile(pitPath, "Master", server: "TheMaster");
		var clientPit = new Pit(pitPath, readOnly: false, autoload: false, subscriber: "pits");
		clientPit.Load(undercover: true);
		clientPit.MergeChanges();
		Assert.NotNull(clientPit.Get("PeerItem"));
		var changeFiles = clientPit.PitDir.EnumerateFiles("*.json")
			.Where(f => f.Name != clientPit.JsonFile.Name).ToList();
		Assert.NotEmpty(changeFiles);
	}
	#endregion
}
